apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        name: techtrends
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.containers.containerPort }}
          protocol: TCP
        livenessProbe:
           httpGet:
             path: {{ .Values.containers.livenessProbe.path }}
             port: {{ .Values.containers.livenessProbe.port }}
        readinessProbe:
           httpGet:
             path: {{ .Values.containers.readinessProbe.path }}
             port: {{ .Values.containers.readinessProbe.port }}
        resources:
          requests:
            memory: {{ .Values.resources.request.memory }}
            cpu: {{ .Values.resources.request.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
