namespace:
  name: sandbox

image:
  name: techtrends 
  repository: nedd29
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  request:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

containers:
  containerPort: 3111
  livenessProbe:
    path: "/healthz"
    port: 3111
  readinessProbe:
    path: "/healthz"
    port: 3111