namespace:
  name: staging

image:
  name: techtrends
  repository: nedd29
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  request:
    memory: "90Mi"
    cpu: "300m"
  limits:
    memory: "128Mi"
    cpu: "500m"

service:
  port: 5111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

containers:
  containerPort: 3111
  livenessProbe:
    path: "/healthz"
    port: 3111
  readinessProbe:
    path: "/healthz"
    port: 3111